import fs from 'node:fs';
function edit(file,fn){const old=fs.readFileSync(file,'utf8');const next=fn(old);if(fs.readFileSync(file,'utf8')!==old)throw Error('Concurrent edit: '+file);fs.writeFileSync(file,next);}
edit('src/engine.mjs',s=>s.replace("this.s.archon=this.pick", "for(let warmup=0;warmup<8;warmup++)this.rand();\n this.s.archon=this.pick").replace("resolveTile(){const s=this.s,f=s.field", "resolveTile(){if(this.s.pendingArmor){this.s.pendingTile=true;return;}const s=this.s,f=s.field").replace("this.addItem(id);break;}\n case 'declineArmor':delete s.pendingArmor;break;", "this.addItem(id);if(s.pendingTile){delete s.pendingTile;this.resolveTile();}break;}\n case 'declineArmor':delete s.pendingArmor;if(s.pendingTile){delete s.pendingTile;this.resolveTile();}break;").replace("let n=(f.hpDamage?c.hp:f.damage||0)+(c.upgrade?d.upgrade?.bonus||0:0);", "let n=f.hpDamage?c.hp:f.damage?f.damage+(c.upgrade?d.upgrade?.bonus||0:0):0;").replace("if(d.unplaceable||cost>b.focus)continue;for(let i=0;i<20;i++)if(this.canStack(c,b.grid[i]))", "if(d.unplaceable||cost>b.focus)continue;for(let i=0;i<20;i++)if(this.canStack(c,b.grid[i])&&(d.type!=='Hex'||d.condition!=='isolated'||this.neighbors(i).length===0))"));
edit('src/content.mjs',s=>s.replace("const hit=n=>({damage:n});", "const hit=n=>({damage:n});").replace("'Transmute','Arcane'", "'Transmute','Arcane'"));
// Druid can discover the two spatial utility spells through its shared common pool.
edit('src/engine.mjs',s=>s.replace("!['transmute','quicksilver','surge'].includes(c.id)","!['surge'].includes(c.id)"));
edit('package.json',s=>{const p=JSON.parse(s.replace(/^\uFEFF/,''));p.scripts.package='node tools/package.mjs';p.scripts['test:gui']='node tools/gui-test.mjs';p.scripts['art:revise']='node tools/revise-art.mjs';return JSON.stringify(p,null,2)+'\n';});
edit('src/ui.mjs',s=>s.replace("import {WeightedPolicy}","import {artPaths} from './art-paths.mjs';\nimport {WeightedPolicy}").replace('src="assets/${id}.png"','src="${artPaths[id]||`assets/${id}.png`}"').replace("const key=s=>", "function tellText(t){return [t.name,t.damage?`${t.damage} ${t.element}${t.hits?' ×'+t.hits:''}`:'',t.pierce?'Pierce':'',t.cull?'Cull':'',t.grid?`${t.grid} ${t.count||1} · ${t.target}`:'',...['burn','poison','corrode'].filter(k=>t[k]).map(k=>k[0].toUpperCase()+k.slice(1)+' '+t[k]),t.insight?`${t.insight} Insight next turn`:'',t.guard?'Gain '+t.guard+' guard':'',t.flicker?'Negate next offensive activation':'',t.howl?'Wolves gain '+t.howl+' attack':''].filter(Boolean).join(' · ');}\nconst key=s=>").replace("${text(e.tell.name)} ${e.tell.damage?`${e.tell.damage} ${e.tell.element}${e.tell.hits?' ×'+e.tell.hits:''}`:''}${e.tell.grid?' · '+e.tell.target:''}","${text(tellText(e.tell))}").replace("spent=c&&d.limit>=0&&c.used>=d.limit", "spent=c&&(c.zeroWard||game.allowance(c,i)===0)").replace("${d.limit<0?'∞':Math.max(0,d.limit-c.used)} acts", "${d.limit<0?'∞':game.allowance(c,i)} acts").replace("${selectedActions.length?`<div", "${selectedSlot!=null&&b.grid[selectedSlot].length?`<div class=\"slot-detail\">${b.grid[selectedSlot].map(c=>`<b>${cards[c.id].name}</b>: ${text(cards[c.id].text)}`).join('<br>')}</div>`:''}${selectedActions.length?`<div"));
const manifest=JSON.parse(fs.readFileSync('reports/art-manifest.json','utf8'));const paths={};for(const m of manifest)paths[m.id]=m.file;fs.writeFileSync('src/art-paths.mjs','export const artPaths = '+JSON.stringify(paths,null,2)+';\n');
